### ISSUE TITLE
Interpolated models via chaiNNer fail in VSGAN

### ISSUE THREAD

**Issue by Selur** [rlaphoenix/VSGAN#35] opened 2023-05-05 11:58 UTC
Interpolating two models that are compatible with VSGAN:
* 2x_Futsuu_Anime_Compact_130k_net_g.pth
* 2x_LD-Anime_Compact_330k_net_g.pth
and use it's interpolate model feature, I get a new .pth model, which isn't compatible with VSGAn any more. :(
```
vsgan.load(model)
File "I:\Hybrid\64bit\Vapoursynth\Lib\site-packages\vsgan\networks\esrgan.py", line 46, in load
model = arch(state)
File "I:\Hybrid\64bit\Vapoursynth\Lib\site-packages\vsgan\archs\ESRGAN.py", line 72, in __init__
self.num_blocks = self.get_num_blocks()
File "I:\Hybrid\64bit\Vapoursynth\Lib\site-packages\vsgan\archs\ESRGAN.py", line 228, in get_num_blocks
return max(*nbs) + 1
TypeError: max expected at least 1 argument, got 0
```
Is there a known way to convert these models, so they are VSGAN compatible again?
Or would it be possible to directly support these models?

**Comment by rlaphoenix** [comment] 2023-05-05 15:13
Those are SRVGGNetCompact models that are not currently supported in VSGAN. These are not ESRGAN models. SRVGGNetCompact aka just Compact are RealESRGAN (v2) models. While the ESRGAN class supports RealESRGAN models, it only supports RealESRGAN v1 models, not v2 models. v1 models use RRDBNet while v2 models use SRVGGNetCompact.

The issue you're having is effectively an early panic when trying to use the model during loading. The use of interpolation wouldn't have caused this. However, the fact you stated that as-is, without interpolation, that they are compatible is quite strange.

**Comment by Selur** [comment] 2023-05-05 15:22
Yes, both models: [2x_Futsuu_Anime_Compact_130k_net_g.zip](https://github.com/rlaphoenix/VSGAN/files/11407718/2x_Futsuu_Anime_Compact_130k_net_g.zip)

**Comment by Selur** [comment] 2023-05-05 18:54
I replaced the Vapoursynth\Lib\site-packages\vsgan in my setup with latest code:
Loading the combi model not works now! :)

**Comment by Selur** [comment] 2023-05-05 21:20
Using this version, combi models work fine, but some other models now produce wrong colors.
```
# Imports
import vapoursynth as vs
import os
import sys
# getting Vapoursynth core
core = vs.core
# Import scripts folder
scriptPath = 'i:/Hybrid/64bit/vsscripts'
sys.path.insert(0, os.path.abspath(scriptPath))
# Loading Plugins
core.std.LoadPlugin(path="i:/Hybrid/64bit/vsfilters/Support/fmtconv.dll")
core.std.LoadPlugin(path="i:/Hybrid/64bit/vsfilters/SourceFilter/LSmashSource/vslsmashsource.dll")
# Import scripts
import mvsfunc
# source: 'G:\TestClips&Co\test.avi'
# current color space: YUV420P8, bit depth: 8, resolution: 640x352, fps: 25, color matrix: 470bg, yuv luminance scale: limited, scanorder: progressive
# Loading G:\TestClips&Co\test.avi using LWLibavSource
clip = core.lsmas.LWLibavSource(source="G:/TestClips&Co/test.avi", format="YUV420P8", stream_index=0, cache=0, prefer_hw=0)
# Setting detected color matrix (470bg).
clip = core.std.SetFrameProps(clip, _Matrix=5)
# Setting color transfer info (470bg), when it is not set
clip = clip if not core.text.FrameProps(clip,'_Transfer') else core.std.SetFrameProps(clip, _Transfer=5)
# Setting color primaries info (), when it is not set
clip = clip if not core.text.FrameProps(clip,'_Primaries') else core.std.SetFrameProps(clip, _Primaries=5)
# Setting color range to TV (limited) range.
clip = core.std.SetFrameProp(clip=clip, prop="_ColorRange", intval=1)
# making sure frame rate is set to 25
clip = core.std.AssumeFPS(clip=clip, fpsnum=25, fpsden=1)
clip = core.std.SetFrameProp(clip=clip, prop="_FieldBased", intval=0) # progressive
# changing range from limited to full range
clip = core.resize.Bicubic(clip, range_in_s="limited", range_s="full")
# Setting color range to PC (full) range.
clip = core.std.SetFrameProp(clip=clip, prop="_ColorRange", intval=0)
# adjusting color space from YUV420P8 to RGBH for vsVSGAN
clip = core.resize.Bicubic(clip=clip, format=vs.RGBH, matrix_in_s="470bg", range_s="full")
# resizing using VSGAN
from vsgan import ESRGAN
vsgan = ESRGAN(clip=clip,device="cuda")
model = "I:/Hybrid/64bit/vsgan_models/4x_BSRGAN.pth"
vsgan.load(model)
vsgan.apply() # 2560x1408
clip = vsgan.clip
# resizing 2560x1408 to 1280x704
# changing range from full to limited range
clip = core.resize.Bicubic(clip, range_in_s="full", range_s="limited")
# Setting color range to TV (limited) range.
clip = core.std.SetFrameProp(clip=clip, prop="_ColorRange", intval=1)
# adjusting resizing
clip = core.resize.Bicubic(clip=clip, format=vs.RGBS, range_s="limited")
clip = core.fmtc.resample(clip=clip, w=1280, h=704, kernel="lanczos", interlaced=False, interlacedd=False)
# adjusting output color from: RGBS to YUV420P10 for NVEncModel
clip = core.resize.Bicubic(clip=clip, format=vs.YUV420P10, matrix_s="470bg", range_s="limited", dither_type="error_diffusion")
# set output frame rate to 25fps (progressive)
clip = core.std.AssumeFPS(clip=clip, fpsnum=25, fpsden=1)
# Output
clip.set_output()
````
using the same model with the old version worked fine.
uploaded the model to [GoogleDrive](https://drive.google.com/file/d/1wwc6Yd3yvRPjH5g93IMqoumXwpwVV1IX/view?usp=share_link)

**Comment by Selur** [comment] 2023-05-06 04:58
Okay, seems like something was still stuck in vram, after a reboot it's working this morning.
Sorry, for the trouble and thank again for the fix.

**Comment by Selur** [comment] 2023-05-06 05:07
Sorry, still broken, I just forgot that I did reset the vsgan files yesterday before going to bed.

**Comment by rlaphoenix** [comment] 2023-05-06 06:03
So with the same exact code, apart from the version of VS, the colors change? Could I see? This isn't really something that could be caused by VSGAN, but could be caused by the model during training. I.e., LR as bt601 and HR as bt709, causing it to convert colors, even if your new LR is bt709, it will still map the colors the same way.

**Comment by Selur** [comment] 2023-05-06 06:13
Yes, using:
```
# Imports
import vapoursynth as vs
import os
import sys
# getting Vapoursynth core
core = vs.core
# Import scripts folder
scriptPath = 'i:/Hybrid/64bit/vsscripts'
sys.path.insert(0, os.path.abspath(scriptPath))
# Loading Plugins
core.std.LoadPlugin(path="i:/Hybrid/64bit/vsfilters/Support/fmtconv.dll")
core.std.LoadPlugin(path="i:/Hybrid/64bit/vsfilters/SourceFilter/LSmashSource/vslsmashsource.dll")
# Import scripts
import mvsfunc
# source: 'G:\TestClips&Co\test.avi'
# current color space: YUV420P8, bit depth: 8, resolution: 640x352, fps: 25, color matrix: 470bg, yuv luminance scale: limited, scanorder: progressive
# Loading G:\TestClips&Co\test.avi using LWLibavSource
clip = core.lsmas.LWLibavSource(source="G:/TestClips&Co/test.avi", format="YUV420P8", stream_index=0, cache=0, prefer_hw=0)
# Setting detected color matrix (470bg).
clip = core.std.SetFrameProps(clip, _Matrix=5)
# Setting color transfer info (470bg), when it is not set
clip = clip if not core.text.FrameProps(clip,'_Transfer') else core.std.SetFrameProps(clip, _Transfer=5)
# Setting color primaries info (), when it is not set
clip = clip if not core.text.FrameProps(clip,'_Primaries') else core.std.SetFrameProps(clip, _Primaries=5)
# Setting color range to TV (limited) range.
clip = core.std.SetFrameProp(clip=clip, prop="_ColorRange", intval=1)
# making sure frame rate is set to 25
clip = core.std.AssumeFPS(clip=clip, fpsnum=25, fpsden=1)
clip = core.std.SetFrameProp(clip=clip, prop="_FieldBased", intval=0) # progressive
# changing range from limited to full range
clip = core.resize.Bicubic(clip, range_in_s="limited", range_s="full")
# Setting color range to PC (full) range.
clip = core.std.SetFrameProp(clip=clip, prop="_ColorRange", intval=0)
# adjusting color space from YUV420P8 to RGBS for vsVSGAN
clip = core.resize.Bicubic(clip=clip, format=vs.RGBS, matrix_in_s="470bg", range_s="full")
# resizing using VSGAN
from vsgan import ESRGAN
vsgan = ESRGAN(clip=clip,device="cuda")
model = "I:/Hybrid/64bit/vsgan_models/4x_BSRGAN.pth"
vsgan.load(model)
vsgan.apply() # 2560x1408
clip = vsgan.clip
# resizing 2560x1408 to 640x352
# changing range from full to limited range
clip = core.resize.Bicubic(clip, range_in_s="full", range_s="limited")
# Setting color range to TV (limited) range.
clip = core.std.SetFrameProp(clip=clip, prop="_ColorRange", intval=1)
# adjusting resizing
clip = core.fmtc.resample(clip=clip, w=640, h=352, kernel="lanczos", interlaced=False, interlacedd=False)
# adjusting output color from: RGBS to YUV420P10 for NVEncModel
clip = core.resize.Bicubic(clip=clip, format=vs.YUV420P10, matrix_s="470bg", range_s="limited", dither_type="error_diffusion")
# set output frame rate to 25fps (progressive)
clip = core.std.AssumeFPS(clip=clip, fpsnum=25, fpsden=1)
# Output
clip.set_output()
```
I get: ![new](https://user-images.githubusercontent.com/843640/236604941-68ad5000-f8b5-4560-9b61-74156963c32e.png)
exchanging the vsgan folder with the old version, I get: 
![old](https://user-images.githubusercontent.com/843640/236605455-a48cce75-69db-4871-a829-8cd684ea972f.png)

**Comment by Selur** [comment] 2023-05-06 06:16
When using 1x_DIV2K-Lite_450k.pth:
old: 
![old2](https://user-images.githu
![new2](https://user-images.githubusercontent.com/843640/236605827-924f2eaa-6527-40a6-8bbe-66b0cc4fdc59.png)
busercontent.com/843640/236605818-a8cc8fa1-dede-4735-bde1-0c7b214e14c0.png)
new:

**Comment by rlaphoenix** [comment] 2023-05-06 06:24
Ok yeah that's definitely not right. When you say "old", how far back did you go? The latest stable release? I will look into this myself very soon and test with that exact model and see what happens.

**Comment by Selur** [comment] 2023-05-06 06:26
Yes, the last stable version (vsgan-1.6.4.dist-info).
[test.zip](https://github.com/rlaphoenix/VSGAN/files/11411632/test.zip) is the source file I used for testing.

**Comment by rlaphoenix** [comment] 2023-05-06 06:43
Very strangely the issue is caused from changing the casing of variables in the RRDB block definition... I have no idea why.

![image](https://user-images.githubusercontent.com/17136956/236607789-a16cb360-965f-437c-9618-b5389796f034.png)

**Comment by Selur** [comment] 2023-05-06 06:44
Okay,.. that is strange.

**Comment by Selur** [comment] 2023-05-06 06:52
I can confirm, after changing those lines, it works here too.

**Comment by rlaphoenix** [comment] 2023-05-06 07:22
I'm gonna close this issue since we have it fixed (but don't know for what reason) but the color issue was also unrelated in the end anyway. Feel free to open another issue if needed.

**Closed by rlaphoenix** 2023-05-06 07:22 UTC
Labels: bug
